networks:
  obligatorio-bases:

services:
  mysql:
    image: docker.io/mysql:9.5.0
    container_name: obligatorio-db
    networks:
      obligatorio-bases:
    environment:
      MYSQL_ROOT_PASSWORD: unsecreto
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_db:/var/lib/mysql
      - ./db/init_salas.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: obligatorio-bases-backend
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: obligatorio-backend
    networks:
      obligatorio-bases:
    ports:
      - 8000:80
