services:
  mysql:
    image: docker.io/mysql:9.5.0
    container_name: obligatorio-db-local
    environment:
      MYSQL_ROOT_PASSWORD: unsecreto

      MYSQL_DATABASE: basesi
      MYSQL_USER: basesi
      MYSQL_PASSWORD: unsecreto
    ports:
      - 3307:3306
    volumes:
      - ./mysql_db:/var/lib/mysql
