services:
  mysql:
    image: docker.io/mysql:9.5.0
    container_name: obligatorio-db-local
    environment:
      MYSQL_ROOT_PASSWORD: unsecreto
      MYSQL_DATABASE: ucu_salas
      MYSQL_USER: basesi
      MYSQL_PASSWORD: unsecreto
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ./01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./02_insert_data.sql:/docker-entrypoint-initdb.d/02_insert_data.sql

volumes:
  mysql_data:
